# GitHub Sponsors configuration
# Only include the desired sponsor name as a custom entry
# See: https://docs.github.com/sponsors/getting-started-with-github-sponsors/about-funding.yml
custom:
 https://github.com/shakti49
